development:
  title:     '2020 Southeast Interscholastic Championships'
  hotfolder: results
  max_time:  180

test:
  title:     '2020 Southeast Interscholastic Championships'
  hotfolder:  results
  max_time:   180